drop table if exists chatroom_master CASCADE;

create table chatroom_master (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_by uuid not null REFERENCES auth.users(id) default auth.uid(),
  name text not null
);

drop table if exists chat_history CASCADE;

create table chat_history (
  id bigint generated by default as identity primary key,
  room bigint not null REFERENCES chatroom_master(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_by uuid not null REFERENCES auth.users(id) default auth.uid(),
  content text not null
);

create index history_room_index
on chat_history
(room);